### ISSUE TITLE
Invalid Handle

### ISSUE THREAD

**Issue by bouldrini** [goblinfactory/konsole#58] opened 2020-04-11 11:44 UTC
I receive Invald Handle Exception when running 
    
    ProgressBar bar = new ProgressBar(PbStyle.DoubleLine, m);

in a Windows Application.
In Console Application this works very well. 
Is there a workaround to use library in Windows Applications Output Window ?

**Comment by goblinfactory** [comment] 2020-04-12 22:03
Hi @bouldrini 
you need to either use Konsole from within a console application, or write an IConsole provider. The current version of Konsole has a faulty interface for IHighSpeedWriter which is essentially what should be used, and all youd need to do is implement that for windows forms, That will be fixed in the next release, and will be replaced with a IConsoleProvider, with a much simpler interface that should be used to allow Konsole to be used in a new platform of any kind.

I will probably write a windows forms provider for Konsole, that will be based on RichText control using fixedWidth font. Please remind in a two weeks time and I'll take a look at putting together a small prototype and add that to the next release.

https://github.com/goblinfactory/konsole/blob/master/src/Konsole/Platform/IHighspeedWriter.cs

is faulty, printAt  is missing `void PrintAt(Colors colors, int x, int y, char c);` (roughtly) I will need to double check this specifically.

```
    public interface IHighspeedWriter : IDisposable
    {
        void ClearScreen();
        char ClearScreenChar { get; set; }

        Colors Colors { get; set; }
        void Flush();

        bool AutoFlush { get; }
 
     // missing!
        void PrintAt(Colors colors, int x, int y, char c);
     // missing
     int Width { get; }
     int Height { get; }
     // missing cursor settings, visible, and position
    }
```

this is not a bug, because it's not a planned feature for this release, so will leave this comment here for a bit, then will close as 'will be added to next major release'.

**Comment by goblinfactory** [comment] 2020-11-13 07:36
closing this issue as not a bug. replacing  with new feature request, for winforms console control. should be fun to write.

**Closed by goblinfactory** 2020-11-13 07:36 UTC
Labels: not a bug - kept open due to valuable discussion
